name: svg_bin_example
description: Example project demonstrating svg_bin usage

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.6.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  svg_bin:
    path: ../
  vector_graphics: ^1.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons-bin/
    - assets/icons-bin/st-icons/
    - assets/icons-bin/nav_icons/
