name: svg_bin
description: "A flutter pacakge that compiles your svg to vec and helps display vec"

version: 0.2.0

repository: https://github.com/arjablc/svg_bin
issue_tracker: https://github.com/arjablc/svg_bin/issues
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  args: ^2.7.0
  flutter:
    sdk: flutter
  path: ^1.9.0
  vector_graphics: ^1.1.18
  vector_graphics_compiler: ^1.1.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
