import 'dart:io';

import 'package:path/path.dart' as path;
import 'package:svg_bin/src/models/asset_tree.dart';
import 'package:svg_bin/src/utils.dart';

class DartGenerator {
  final bool generateAllGetter;

  DartGenerator({this.generateAllGetter = false});

  String generate(AssetTree tree) {
    _validateIdentifiers(tree);

    final buffer = StringBuffer()
      ..writeln('// GENERATED FILE - DO NOT EDIT BY HAND')
      ..writeln('// Generated by svg_bin')
      ..writeln();

    _writeAppAssetClass(buffer, tree);
    for (final folder in tree.folders) {
      buffer.writeln();
      _writeAssetClass(buffer, Utils.toPascalCase(folder.name), folder.files,
          folder.categories);
      for (final category in folder.categories) {
        buffer.writeln();
        _writeAssetClass(
          buffer,
          Utils.toPascalCase(category.name),
          category.files,
          const [],
        );
      }
    }
    return buffer.toString();
  }

  void _writeAppAssetClass(StringBuffer buffer, AssetTree tree) {
    buffer.writeln('final class AppAsset {');
    for (final folder in tree.folders) {
      final className = Utils.toPascalCase(folder.name);
      final getterName = Utils.toCamelCase(folder.name);
      buffer.writeln('  static const $getterName = $className();');
    }
    buffer.writeln('}');
  }

  void _writeAssetClass(
    StringBuffer buffer,
    String className,
    List<AssetFile> files,
    List<AssetCategory> categories,
  ) {
    buffer
      ..writeln('final class $className {')
      ..writeln('  const $className();');

    if (files.isNotEmpty || categories.isNotEmpty) buffer.writeln();
    for (final file in files) {
      final getterName = Utils.toCamelCase(file.name);
      buffer.writeln(
          "  String get $getterName => '${_assetPath(file.outputPath)}';");
    }
    for (final category in categories) {
      final className = Utils.toPascalCase(category.name);
      final getterName = Utils.toCamelCase(category.name);
      buffer.writeln('  $className get $getterName => $className();');
    }
    if (generateAllGetter && files.isNotEmpty) {
      buffer.writeln();
      buffer.writeln('  List<String> get all => [');
      for (final file in files) {
        buffer.writeln('    ${Utils.toCamelCase(file.name)},');
      }
      buffer.writeln('  ];');
    }
    buffer.writeln('}');
  }

  void _validateIdentifiers(AssetTree tree) {
    final classes = <String, String>{'AppAsset': 'generated root class'};
    final rootGetters = <String, String>{};

    for (final folder in tree.folders) {
      _claim(
          classes, Utils.toPascalCase(folder.name), folder.sourcePath, 'class');
      _claim(
        rootGetters,
        Utils.toCamelCase(folder.name),
        folder.sourcePath,
        'AppAsset member',
      );
      _validateMembers(folder.files, folder.categories);

      for (final category in folder.categories) {
        _claim(
          classes,
          Utils.toPascalCase(category.name),
          category.sourcePath,
          'class',
        );
        _validateMembers(category.files, const []);
      }
    }
  }

  void _validateMembers(
    List<AssetFile> files,
    List<AssetCategory> categories,
  ) {
    final members = <String, String>{};
    if (generateAllGetter && files.isNotEmpty) {
      members['all'] = 'generated all getter';
    }
    for (final file in files) {
      _claim(members, Utils.toCamelCase(file.name), file.sourcePath, 'member');
    }
    for (final category in categories) {
      _claim(
        members,
        Utils.toCamelCase(category.name),
        category.sourcePath,
        'member',
      );
    }
  }

  void _claim(
    Map<String, String> identifiers,
    String identifier,
    String sourcePath,
    String kind,
  ) {
    final existing = identifiers[identifier];
    if (existing != null) {
      throw StateError(
        '$kind "$identifier" is generated by both "$existing" and "$sourcePath".',
      );
    }
    identifiers[identifier] = sourcePath;
  }

  String _assetPath(String absolutePath) => path
      .relative(absolutePath, from: Directory.current.path)
      .replaceAll(path.separator, '/');
}
