import 'package:path/path.dart' as path;
import 'package:svg_bin/src/models/asset.dart';
import 'package:svg_bin/src/utils.dart';

class DartGenerator {
  final bool generateAllGetter;

  DartGenerator({this.generateAllGetter = false});

  String generate(List<Asset> assets) {
    final root = _buildTree(assets);
    _validateIdentifiers(root);

    final buffer = StringBuffer()
      ..writeln('// GENERATED FILE - DO NOT EDIT BY HAND')
      ..writeln('// Generated by svg_bin')
      ..writeln();

    _writeRootClass(buffer, root);
    _writeChildren(buffer, root);
    return buffer.toString();
  }

  _AssetNode _buildTree(List<Asset> assets) {
    final root = _AssetNode();
    for (final asset in assets) {
      var node = root;
      final segments = path.split(asset.relativePath);
      for (final segment in segments.take(segments.length - 1)) {
        node = node.children.putIfAbsent(segment, _AssetNode.new);
      }
      node.assets.add(asset);
    }
    return root;
  }

  void _writeRootClass(StringBuffer buffer, _AssetNode root) {
    buffer.writeln('final class AppAsset {');
    for (final asset in root.assets) {
      buffer.writeln(
        "  static const ${Utils.toCamelCase(asset.name)} = '${asset.runtimePath}';",
      );
    }
    for (final entry in root.children.entries) {
      buffer.writeln(
        '  static const ${Utils.toCamelCase(entry.key)} = ${_className([
              entry.key
            ])}();',
      );
    }
    _writeAll(buffer, root.assets, isStatic: true);
    buffer.writeln('}');
  }

  void _writeChildren(StringBuffer buffer, _AssetNode root) {
    void visit(_AssetNode node, List<String> segments) {
      for (final entry in node.children.entries) {
        final childSegments = [...segments, entry.key];
        buffer.writeln();
        _writeAssetClass(buffer, entry.value, childSegments);
        visit(entry.value, childSegments);
      }
    }

    visit(root, const []);
  }

  void _writeAssetClass(
    StringBuffer buffer,
    _AssetNode node,
    List<String> segments,
  ) {
    final className = _className(segments);
    buffer
      ..writeln('final class $className {')
      ..writeln('  const $className();');

    if (node.assets.isNotEmpty || node.children.isNotEmpty) buffer.writeln();
    for (final asset in node.assets) {
      buffer.writeln(
        "  String get ${Utils.toCamelCase(asset.name)} => '${asset.runtimePath}';",
      );
    }
    for (final entry in node.children.entries) {
      final childSegments = [...segments, entry.key];
      final childClassName = _className(childSegments);
      buffer.writeln(
        '  $childClassName get ${Utils.toCamelCase(entry.key)} => const $childClassName();',
      );
    }
    _writeAll(buffer, node.assets);
    buffer.writeln('}');
  }

  void _writeAll(
    StringBuffer buffer,
    List<Asset> assets, {
    bool isStatic = false,
  }) {
    if (!generateAllGetter || assets.isEmpty) return;

    buffer.writeln();
    buffer.writeln(
        '  ${isStatic ? 'static const' : 'List<String> get'} all ${isStatic ? '=' : '=>'} [');
    for (final asset in assets) {
      buffer.writeln('    ${Utils.toCamelCase(asset.name)},');
    }
    buffer.writeln('  ];');
  }

  void _validateIdentifiers(_AssetNode root) {
    final classes = <String, String>{'AppAsset': 'generated root class'};
    void visit(_AssetNode node, List<String> segments) {
      _validateMembers(node);
      for (final entry in node.children.entries) {
        final childSegments = [...segments, entry.key];
        _claim(
          classes,
          _className(childSegments),
          childSegments.join('/'),
          'class',
        );
        visit(entry.value, childSegments);
      }
    }

    visit(root, const []);
  }

  void _validateMembers(_AssetNode node) {
    final members = <String, String>{};
    if (generateAllGetter && node.assets.isNotEmpty) {
      members['all'] = 'generated all getter';
    }
    for (final asset in node.assets) {
      _claim(
          members, Utils.toCamelCase(asset.name), asset.relativePath, 'member');
    }
    for (final entry in node.children.entries) {
      _claim(
        members,
        Utils.toCamelCase(entry.key),
        entry.key,
        'member',
      );
    }
  }

  void _claim(
    Map<String, String> identifiers,
    String identifier,
    String sourcePath,
    String kind,
  ) {
    final existing = identifiers[identifier];
    if (existing != null) {
      throw StateError(
        '$kind "$identifier" is generated by both "$existing" and "$sourcePath".',
      );
    }
    identifiers[identifier] = sourcePath;
  }

  String _className(List<String> segments) =>
      segments.map(Utils.toPascalCase).join();
}

class _AssetNode {
  final List<Asset> assets = [];
  final Map<String, _AssetNode> children = {};
}
