import 'dart:io';

import 'package:path/path.dart' as path;
import 'package:svg_bin/src/models/asset_tree.dart';
import 'package:svg_bin/src/utils.dart';

class DartGenerator {
  final String assetRoot;

  DartGenerator({this.assetRoot = 'assets'});

  String generate(AssetTree tree) {
    final buffer = StringBuffer()
      ..writeln("// GENERATED FILE - DO NOT EDIT BY HAND")
      ..writeln("// Generated by svg_bin")
      ..writeln()
      ..write(_generateAppAssetClass(tree))
      ..writeln()
      ..writeAll(tree.folders.map(_generateFolderClass));

    return buffer.toString();
  }

  String _generateAppAssetClass(AssetTree tree) {
    final buffer = StringBuffer()
      ..writeln('final class AppAsset {')
      ..writeAll(
        tree.folders.map((folder) {
          final className = Utils.toPascalCase(folder.name);
          final instanceName = Utils.toCamelCase(folder.name);
          return '  static const $instanceName = $className();${Platform.lineTerminator}';
        }),
      )
      ..writeln('}');

    return buffer.toString();
  }

  String _generateFolderClass(AssetFolder folder) {
    final className = Utils.toPascalCase(folder.name);
    final buffer = StringBuffer()
      ..writeln('final class $className {')
      ..writeln('  const $className();')
      ..writeln();

    for (final file in folder.files) {
      final getterName = Utils.toCamelCase(file.name);
      final relativePath = _toRelativeAssetPath(file.outputPath);
      buffer.writeln("  String get $getterName => '$relativePath';");
    }

    for (final category in folder.categories) {
      final catClassName = Utils.toPascalCase(category.name);
      final catInstanceName = Utils.toCamelCase(category.name);
      buffer.writeln('  $catClassName get $catInstanceName => $catClassName();');
    }

    if (folder.files.isNotEmpty) {
      buffer.writeln();
      buffer.writeln('  List<String> get all => [');
      for (final file in folder.files) {
        final getterName = Utils.toCamelCase(file.name);
        buffer.writeln('    $getterName,');
      }
      buffer.writeln('  ];');
    }

    buffer.writeln('}');

    for (final category in folder.categories) {
      buffer.write(_generateCategoryClass(category, folder.name));
    }

    return buffer.toString();
  }

  String _generateCategoryClass(AssetCategory category, String folderName) {
    final className = Utils.toPascalCase(category.name);
    final buffer = StringBuffer()
      ..writeln()
      ..writeln('final class $className {')
      ..writeln('  const $className();')
      ..writeln();

    for (final file in category.files) {
      final getterName = Utils.toCamelCase(file.name);
      final relativePath = _toRelativeAssetPath(file.outputPath);
      buffer.writeln("  String get $getterName => '$relativePath';");
    }

    buffer.writeln();
    buffer.writeln('  List<String> get all => [');
    for (final file in category.files) {
      final getterName = Utils.toCamelCase(file.name);
      buffer.writeln('    $getterName,');
    }
    buffer.writeln('  ];');

    buffer.writeln('}');

    return buffer.toString();
  }

  String _toRelativeAssetPath(String absolutePath) {
    final cwd = Directory.current.path;
    var relative = path.relative(absolutePath, from: cwd);
    relative = relative.replaceAll(path.separator, '/');
    return relative;
  }
}
