// GENERATED FILE - DO NOT EDIT BY HAND
// Generated by svg_bin

final class AppAsset {
  static const icons = Icons();
}

final class Icons {
  const Icons();

  String get star => 'assets/icons-bin/star.svg.vec';
  IconsNavIcons get navIcons => const IconsNavIcons();
  IconsStIcons get stIcons => const IconsStIcons();

  List<String> get all => [
    star,
  ];
}

final class IconsNavIcons {
  const IconsNavIcons();

  String get arrowLeft => 'assets/icons-bin/nav_icons/arrow-left.svg.vec';
  String get arrowRight => 'assets/icons-bin/nav_icons/arrow_right.svg.vec';

  List<String> get all => [
    arrowLeft,
    arrowRight,
  ];
}

final class IconsStIcons {
  const IconsStIcons();

  String get homeIcon => 'assets/icons-bin/st-icons/home-icon.svg.vec';
  String get settingsIcon => 'assets/icons-bin/st-icons/settings_icon.svg.vec';

  List<String> get all => [
    homeIcon,
    settingsIcon,
  ];
}
