// GENERATED FILE - DO NOT EDIT BY HAND
// Generated by svg_bin

final class AppAsset {
  static const icons = Icons();
}

final class Icons {
  const Icons();

  String get star => 'assets/icons-bin/star.svg.vec';
  StIcons get stIcons => StIcons();
  NavIcons get navIcons => NavIcons();

  List<String> get all => [
    star,
  ];
}

final class StIcons {
  const StIcons();

  String get homeIcon => 'assets/icons-bin/st-icons/home-icon.svg.vec';
  String get settingsIcon => 'assets/icons-bin/st-icons/settings_icon.svg.vec';

  List<String> get all => [
    homeIcon,
    settingsIcon,
  ];
}

final class NavIcons {
  const NavIcons();

  String get arrowLeft => 'assets/icons-bin/nav_icons/arrow-left.svg.vec';
  String get arrowRight => 'assets/icons-bin/nav_icons/arrow_right.svg.vec';

  List<String> get all => [
    arrowLeft,
    arrowRight,
  ];
}
