// GENERATED FILE - DO NOT EDIT BY HAND
// Generated by path_gen

final class AppAsset {
  static const icons = Icons();
}

final class Icons {
  const Icons();

  String get star => 'assets/icons/star.svg';
  IconsNavIcons get navIcons => const IconsNavIcons();
  IconsStIcons get stIcons => const IconsStIcons();

  List<String> get all => [
        star,
      ];
}

final class IconsNavIcons {
  const IconsNavIcons();

  String get arrowLeft => 'assets/icons/nav_icons/arrow-left.svg';
  String get arrowRight => 'assets/icons/nav_icons/arrow_right.svg';

  List<String> get all => [
        arrowLeft,
        arrowRight,
      ];
}

final class IconsStIcons {
  const IconsStIcons();

  String get homeIcon => 'assets/icons/st-icons/home-icon.svg';
  String get settingsIcon => 'assets/icons/st-icons/settings_icon.svg';

  List<String> get all => [
        homeIcon,
        settingsIcon,
      ];
}
